[package]
name = "tramsformer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.80"
dialoguer = "0.11.0"
wasmtime = { version = "18.0.2", features = ["component-model"] }
