[package]
name = "tramsformer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.80"
dialoguer = "0.11.0"
wasmtime = "21.0.1"
wasmtime-wasi = "21.0.1"
