spin_manifest_version = 2

[application]
name = "acme"
version = "0.1.0"
authors = ["Thorsten Hans <thorsten.hans@fermyon.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "acme"

[component.acme]
source = "composed.wasm"
sqlite_databases = ["default"]
allowed_outbound_hosts = ["http://localhost:3001", "http://localhost:3002"]

[component.acme.build]
command = "cargo component build --release"
watch = ["src/**/*.rs", "Cargo.toml"]
